### ISSUE TITLE
Question: How to get a specific URL query parameter

### ISSUE THREAD

**Issue by av4625** [boostorg/url#682]
Hi,

I wanted to get a specific query parameter and I used `find` to see if it existed and then wanted to return the `value`. But I noticed that `->` has been deleted from the iterator so I can't do `param->value`, but I can do `(*param).value`.

Here is the sort of function that I want:
```
std::string request_impl::get_query_param(const std::string& key) const
{
    const boost::urls::url_view url(request_.target());

    const auto param{url.params().find(key)};

    if (param != url.params().end())
    {
        // -> is deleted
        return (*param).value;
    }

    throw std::invalid_argument(key + " does not exist as a query parameter");
}
```

Is what I have the "right" way to do it or is there a better way that I'm missing?

What is the reason for deleting `->` but allowing `(*param).value`?

Thanks!

**Comment by vinniefalco** [comment]
Every time you invoke `operator*` or `operator->` it applies percent-decoding to produce the value. The idiomatic usage is:
```
auto const qp( *it );
// access qp.key and qp.value
```

This way the percent-decoding is only applied once, and you can access the key and value many times. Your way is okay too, because you are only applying the percent-decoding once. `operator->` is omitted as a gentle reminder of the cost of dereferencing.

**Comment by av4625** [comment]
Thanks for the reply!
