### ISSUE TITLE
Crash in constructor with character 'å'

### ISSUE THREAD

**Issue by Dangeroustuber** [boostorg/url#683]
Hello, i have a HTTPS server where I'm trying to construct a URL object with the following std::string: 
```cpp
?limit=100&query=eq(RpOmrÃ¥de/arealplanid/planidentifikasjon,63280000)
```

I'm using postman to send the request to the server and it sends the string like this to the server: 
```cpp
?limit=100&query=eq(RpOmr%C3%A5de/arealplanid/planidentifikasjon,63280000)
```

code snippet:
```cpp
auto par = boost::url{query_parameters}; // code that is throwing
```

this is the exception message when i catch it with a general exception: `leftover [boost.url.bnf:4]`

I've tried turning the string from UTF8 to regular std::string where the 'å' is represented correctly but it still crashes in the constructor.
If you try to construct it like this: "limit=100&query=eq(RpOmrade/arealplanid/planidentifikasjon,63280000)" without the 'å' character, that does not throw any error.

This is using the 1.80 version and i'm using MSVC on windows. Thanks for any help and let me know if you need any more information.

**Comment by vinniefalco** [comment]
This program throws, because URLs cannot contain high-ascii characters:

https://godbolt.org/z/KE6qjeG9K

This program does not throw, as it contains only valid characters:

https://godbolt.org/z/zErv3Yh1P

You said:
> I've tried turning the string from UTF8 to regular std::string where the 'å' is represented correctly but it still crashes in the constructor.

Can you please post a small, complete program on Compiler Explorer that crashes, which I can run myself to see the problem?

**Comment by vinniefalco** [comment]
I think there's a misunderstanding here. "å'" is _not a valid character_ in a URL. It must be percent-escaped. Boost.URL only allows valid URLs to be parsed (otherwise it would be non-compliant with the RFC). If you want a particular character in the resulting URL you will need to assemble it using the modifier functions which accept plain strings, like this:

```
    boost::urls::url u;
    u.params().append( { "limit", "100" } );
    u.params().append( { "query",
        "eq(RpOmr%C3%A5de/arealplanid/planidentifikasjon,63280000)" } );
```

alternatively, you can write:

```
    boost::urls::url u;
    u.set_query( 
        "?limit=100&query=eq(RpOmr%C3%A5de/arealplanid/planidentifikasjon,63280000)" );
```

**Comment by Dangeroustuber** [comment]
> When you set part of a URL using a plain string, the library will automatically apply percent-encoding for you as needed.

But in the example you already have it percent encoded? maybe i'm misunderstanding?

Do i have to fix the string myself for all cases that i care about? postman does send it correctly but by the time it gets to the std::string it's like in the first post on this issue, which is not correct.

**Comment by Dangeroustuber** [comment]
Right thanks so much, so something like this would work if i understood you correctly:

```
auto newstr = convert_string_from_UTF8(query_parameters);

boost::urls::url par;
par.set_query(newstr);
```

If i give boost::url something with 'å' for example, it will "fix" that for me.

**Comment by vinniefalco** [comment]
yes

**Comment by Dangeroustuber** [comment]
Yes, that is a good suggestion. Thanks for all the help, i'm closing the issue.
