### ISSUE TITLE
boost/url/src.hpp must be included before other boost/url headers to make boost/url header-only: documentation change needed

### ISSUE THREAD

**Issue by GrahamAsher** [boostorg/url#696]
I used this code in a project compiled using Microsoft Visual Studio 2022 (Microsoft Visual Studio Community 2022 (64-bit) - Version 17.4.5):

```
#include <boost/url/parse.hpp>
#include <boost/url/src.hpp>
```

and got a link error stating that a library was required. The documentation says that header-only use of boost/url can be achieved if boost/url/src.hpp is included. It should be amended to say that boost/url/src.hpp has to be included before any other boost/url files. I verified this by changing my code to

```
#include <boost/url/src.hpp>
#include <boost/url/parse.hpp>
```

which prevented the link error from occurring.

**Comment by vinniefalco** [comment]
You also have to define BOOST_URL_NO_LIB if you are using Visual Studio. Then, the order won't matter.

**Comment by vinniefalco** [comment]
The documentation should say "Visual Studio users must also define the macro `BOOST_URL_NO_LIB` to disable auto-linking"

**Comment by GrahamAsher** [comment]
Hi Vinnie, thank you for acknowledging this problem. It's much easier to use header-only libraries, so in general the way to do that should be made as clear as possible.

**Comment by alandefreitas** [comment]
> "Visual Studio users must also define the macro BOOST_URL_NO_LIB to disable auto-linking"

"MSVC users must also define the macro BOOST_URL_NO_LIB to disable auto-linking"?

**Comment by vinniefalco** [comment]
Yeah that sounds good

**Comment by alandefreitas** [comment]
I just checked and the documentation already says that in much more detail. I just remembered we had a long discussion a long time ago where we came up with a template to use in boost.url and other libs.

As this issue indicates, we **could** mention in the docs that things will also work when you forget `BOOST_URL_NO_LIB` and include `#include <boost/url/src.hpp>` before anything else because it also enforces `BOOST_URL_NO_LIB`.

But that would only make things more confusing and incentivize bad behavior.
